---
# tasks file for wordpress

#---------------install--------------

- name: install wordpress
  apt:
    pkg: wordpress
    
#----------------configure apache-----------------
    
- name: check wordpress config
  stat:
    path: /etc/apache2/sites-available/wp.conf
  register: conf_file
    
- name: add wordpress config
  copy: 
    src: wp.conf
    dest: /etc/apache2/sites-available/wp.conf
  when: not conf_file.stat.exists
  
- name: disable & enable sites
  shell: a2dissite 000-default && a2ensite wp
  when: not conf_file.stat.exists 
  
#-----------configure wordpress------------

#- name: confugre wordpress

  
#---------------run---------------------

- name: reload apache2
  systemd:
    name: apache2
    state: reloaded
  when: not conf_file.stat.exists



