proxy:
  hosts:
    bms-devops.ru:
      ansible_user: root
      ansible_ssh_user: root
nodes:
  hosts:
    nginx:
      ansible_host: 172.16.0.100
    db01:
      ansible_host: 172.16.0.101
    db02:
      ansible_host: 172.16.0.102
    app:
      ansible_host: 172.16.0.103
    gitlab:
      ansible_host: 172.16.0.104
  vars:
    ansible_user: root
    ansible_ssh_user: root
    ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -p 22 -W %h:%p -q root@bms-devops.ru"
