---
# tasks file for mysql
- name: prepare for mysql installation
  apt:
    pkg:
      - gnupg
      - lsb-release
      
- name: download last release
  shell: wget https://dev.mysql.com/get/{{ mysql_last_repo_deb }}

- name: install downloaded deb
  apt:
    deb: ./{{ mysql_last_repo_deb }}
  environment:
    DEBIAN_FRONTEND: noninteractive

#seems no cluster needed, just replication
#- name: reconfigure to cluster
#  shell: sed -i 's/-[0-9]\+\.[0-9]\+/-cluster\0/g' /etc/apt/sources.list.d/mysql.list
  
- name: update apt
  shell: apt update
  
- name: install mysql server
  apt:
    pkg: mysql-community-server
    #
    #mysql-cluster-community-server
  environment:
    DEBIAN_FRONTEND: noninteractive
    
#pick master of slave config
- name: add mysqld {{ db_kind }} config
  copy: 
    src: mysqld_{{ db_kind }}.cnf
    dest: /etc/mysql/mysql.conf.d/mysql.cnf
  #when: db_kind == "master"  

- name: restart mysql
  shell: systemctl restart mysql

#TODO: execute SQL SETUP user password & replication  
  
#TODO: change root password
#https://www.youtube.com/watch?v=RkbIqbXCWqI master-slave, master-master config


  
