- name: hello
  hosts: nodes
  tasks:
    - name: install nginx
      apt:
        pkg: 
          - nginx 
          - certbot 
          - python3-certbot-nginx 
          - python3-acme 
          - python3-certbot
        state: latest
    - name: prepare nginx
      shell: sed -i 's/_;/bms-devops.ru;/g' /etc/nginx/sites-available/default
    - name: prepare for certbot
      shell: mkdir -p /var/www/html/.well-known/acme-challenge/
    - name: configure certbot
      shell: certbot --test-cert --nginx -d bms-devops.ru --register-unsafely-without-email -n --agree-tos
