---
# tasks file for gitlab
- name: install packages
  apt:
    pkg:
    - curl
    - ca-certificates
    - apt-transport-https
    - gnupg2
    
- name: get and install
  shell: curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash

- name: apt update
  apt:
    update_cache: yes

- name: install gitlab-ce
  apt:
    pkg: gitlab-ce
    
#TODO: copy preconfigured config with prometheus and either
- name: modify config file
  shell: sed -i "s/external_url 'http:\/\/gitlab.example.com'/external_url 'http:\/\/gitlab.bms-devops.ru'/g" /etc/gitlab/gitlab.rb
  
- name: gitlab reconfigure
  shell: gitlab-ctl reconfigure
  
- name: gathering password
  fetch:
    src: /etc/gitlab/initial_root_password
    dest: /tmp/
    
- debug:
    msg: 'gitlab temp password now int /tmp/initial_root_password'
    

